"""Bounded context: auditoría, seguridad, observabilidad y configuración.

Contiene: AuditLog, ConsentAuditLog, AdminAlertSeverity, AdminAlert,
ImpersonationScope, ImpersonationSession, AIUsageLog, ErrorLog,
FeatureFlag, AIPrompt, IntegrationConfig.

Migrations 012, 034, 035, 036 · GH-S8-BE-10 · GH-S11.5 · GH-SUPERADMIN-EXPERIENCE.
"""
import enum
import uuid
from datetime import datetime

from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID

from app.db.models.base import Base


class AdminAlertSeverity(str, enum.Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class ImpersonationScope(str, enum.Enum):
    READ_ONLY = "read_only"
    READ_WRITE = "read_write"


class AuditLog(Base):
    """Audit trail of sensitive admin actions · GH-S8-BE-10.

    Logs every super_admin and school_admin mutation. Read-only from the
    panel (no edit/delete via API). Retention >= 1 year per Habeas Data
    operative compliance.
    """

    __tablename__ = "audit_logs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    action = Column(String(80), nullable=False, index=True)
    resource_type = Column(String(60), nullable=False, index=True)
    resource_id = Column(String(120), nullable=True, index=True)
    payload = Column(JSON, nullable=True)
    ip_address = Column(String(60), nullable=True)
    user_agent = Column(String(255), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class ConsentAuditLog(Base):
    """Immutable audit trail for consent grants and revocations.

    GH-S11.5-BE-07 · D-026 · Ley 1581/2012 (Colombia) · Art. 8.

    Each row records a single consent state transition (or data right
    exercise) for a user. `event` is whitelisted by the service layer
    (NOT a DB enum · enables extension without migrations).

    Valid `event` values (curated whitelist · enforced in
    `app.services.consent_service.CONSENT_EVENTS`):

        data_processing.granted   · global Privacy Policy accepted
        data_processing.revoked   · titular asks for cessation
        crm_sync.granted          · opt-in to Bitrix share
        crm_sync.revoked          · opt-out / right to revoke
        parental.granted          · legal guardian authorization
        parental.revoked          · guardian withdraws authorization
        data_export               · titular invoked GET /me/data
        data_deletion             · titular invoked DELETE /me/data

    Read-only by design · no UPDATE / DELETE expected. user_id stays
    populated even after the user is soft-deleted (FK uses SET NULL).
    """

    __tablename__ = "consent_audit_log"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    event = Column(String(60), nullable=False, index=True)
    ip = Column(String(50), nullable=True)
    user_agent = Column(String(500), nullable=True)
    policy_version = Column(String(20), nullable=True)
    created_at = Column(
        DateTime,
        default=datetime.utcnow,
        nullable=False,
        index=True,
    )


class AdminAlert(Base):
    """Proactive alert for super_admin attention · Bloque D (migration 034).

    Generated by `admin_alerts_service.run_checks()` (cron-style worker called
    on /admin/alerts/refresh or background scheduler). One row per
    (type, target) while active; resolving stamps `resolved_at` so a fresh
    alert can fire later.
    """

    __tablename__ = "admin_alerts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    type = Column(String(60), nullable=False, index=True)
    severity = Column(String(20), nullable=False, default=AdminAlertSeverity.WARNING.value)
    target_type = Column(String(40), nullable=True)
    target_id = Column(String(120), nullable=True)
    title = Column(String(255), nullable=False)
    body = Column(Text, nullable=True)
    data = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    resolved_at = Column(DateTime, nullable=True)
    resolved_by_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )


class ImpersonationSession(Base):
    """Audit trail for super_admin impersonation · Bloque E (migration 034).

    Token grants the actor (super_admin) a session that authenticates as the
    target user with reduced scope. Hard rules enforced by service:
      - actor MUST be super_admin
      - target MUST NOT be super_admin (no peer-impersonation)
      - cannot start a new session while another is active for same actor
      - banner is forced in the FE while ended_at IS NULL
      - every action during the session is also audit-logged with both ids
    """

    __tablename__ = "impersonation_sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    actor_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    target_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    token = Column(String(120), nullable=False, unique=True, index=True)
    scope = Column(String(20), nullable=False, default=ImpersonationScope.READ_ONLY.value)
    started_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    ended_at = Column(DateTime, nullable=True)
    ip_address = Column(String(60), nullable=True)
    user_agent = Column(String(255), nullable=True)


class AIUsageLog(Base):
    """Per-call AI cost ledger · Bloque J (migration 035)."""

    __tablename__ = "ai_usage_log"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    provider = Column(String(20), nullable=False, index=True)
    model = Column(String(80), nullable=False)
    feature = Column(String(60), nullable=False, index=True)
    tokens_input = Column(Integer, nullable=True)
    tokens_output = Column(Integer, nullable=True)
    cost_usd = Column(Float, nullable=True)
    latency_ms = Column(Integer, nullable=True)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class ErrorLog(Base):
    """Captured backend exceptions · Bloque K (migration 035)."""

    __tablename__ = "error_log"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    level = Column(String(10), nullable=False, default="error")
    path = Column(String(255), nullable=True)
    method = Column(String(10), nullable=True)
    status_code = Column(Integer, nullable=True)
    exception_type = Column(String(120), nullable=True, index=True)
    message = Column(Text, nullable=True)
    trace = Column(Text, nullable=True)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    resolved_at = Column(DateTime, nullable=True)


class FeatureFlag(Base):
    """Runtime feature toggle · Bloque M (migration 036).

    Resolution order in `is_feature_enabled(key, user)`:
      1. flag missing → False
      2. flag.enabled is True → True (global on)
      3. user.role in enabled_for_roles → True
      4. user.school_id in enabled_for_school_ids → True
      5. otherwise False
    """

    __tablename__ = "feature_flags"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    key = Column(String(80), nullable=False, unique=True)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    enabled = Column(Boolean, default=False, nullable=False)
    enabled_for_roles = Column(JSON, default=list, nullable=False)
    enabled_for_school_ids = Column(JSON, default=list, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    created_by_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )


class AIPrompt(Base):
    """Versioned AI prompts persisted in DB · Bloque N (migration 036).

    Active prompt per key is resolved via (key, is_active=True). Activating
    a new version flips the previous active row to is_active=False inside a
    single transaction. Services read with TTL cache (60s) to keep latency
    low.
    """

    __tablename__ = "ai_prompts"
    __table_args__ = (
        UniqueConstraint("key", "version", name="uq_ai_prompts_key_version"),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    key = Column(String(80), nullable=False, index=True)
    version = Column(Integer, nullable=False)
    content = Column(Text, nullable=False)
    is_active = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_by_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    notes = Column(Text, nullable=True)


class IntegrationConfig(Base):
    """Per-integration UI-editable settings · Bloque O (migration 036).

    SECURITY:
      - is_secret=True rows have setting_value = env var NAME (e.g.
        "BITRIX_WEBHOOK_URL"). Actual secret values STAY in env. Never copy.
      - is_secret=False rows can carry plain metadata (notify_email,
        sync_interval_minutes, enabled flag).
    """

    __tablename__ = "integration_configs"
    __table_args__ = (
        UniqueConstraint("integration_key", "setting_key", name="uq_integration_configs_key_setting"),
    )

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    integration_key = Column(String(40), nullable=False, index=True)
    setting_key = Column(String(80), nullable=False)
    setting_value = Column(Text, nullable=True)
    is_secret = Column(Boolean, default=False, nullable=False)
    description = Column(Text, nullable=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    updated_by_user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
